CREATE TABLE if NOT EXISTS flight_list
(
    id                  INTEGER generated by default as identity primary key
);

CREATE TABLE if NOT EXISTS segments
(
    id                  INTEGER generated by default as identity primary key,
    departure_date      TIMESTAMP not null,
    arrival_date        TIMESTAMP not null,
    flight_id           INTEGER,
    FOREIGN KEY (flight_id) REFERENCES flight_list (id)
);